version: '3.1'

services:

  monitoring:
    build: ./monitoring
    command: bash -c "
      python data_generator.py
      "
    volumes:
      - ./data:/data
    networks:
      - my-network


  backend:
    build: ./backend
    ports:
      - "5005:5005"
    command: bash -c "
      python run.py
      "
    depends_on:
      - monitoring
    volumes:
      - ./data:/data
    networks:
      - my-network


  frontend:
    build: ./frontend
    ports:
      - 8081:8081
    networks:
      - my-network

networks:
  my-network:
